Doc: Restructure Contributing guide
IntersectMBO/cardano-db-sync pull request #1736
Opened 2024-06-14 20:20 UTC by sgillespie

# Description

Restructure (GET IT?!) Contributing. The purpose is to make it easier to edit

# Checklist

- [ ] Commit sequence broadly makes sense
- [ ] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/IntersectMBO/cardano-db-sync/blob/master/cardano-db-sync/CHANGELOG.md)
- [ ] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) on version 0.10.1.0 (which can be run with `scripts/fourmolize.sh`)
- [ ] Self-reviewed the diff

# Migrations

- [ ] The pr causes a [breaking change](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/migrations.md) of type a,b or c
- [ ] If there is a breaking change, the pr includes a database migration and/or a fix process for old values, so that upgrade is possible
- [ ] Resyncing and running the migrations provided will result in the same database semantically

If there is a breaking change, especially a big one, please add a justification here. Please elaborate
more what the migration achieves, what it cannot achieve or why a migration is not possible.

2024-06-17 08:57 UTC, kderme commented
Seems good. Could there be some words about using nix shell/develop and haskell-language-server?

2024-06-26 18:33 UTC, sgillespie commented
> Seems good. Could there be some words about using nix shell/develop and haskell-language-server?

I've added a bit in there, let me know if you want me to expand or change it in any way

2024-06-28 12:11 UTC, Cmdv approved these changes
Lovely 👌

2024-06-28 18:19 UTC, kderme requested changes

2024-06-28 18:19 UTC, kderme commented on CONTRIBUTING.rst
> +  nix flake lock --update-input nix flake lock --update-input hackageNix
```suggestion
  nix flake lock --update-input hackageNix
```

2024-07-04 08:14 UTC, kderme approved these changes

2024-07-04 08:14 UTC, merged