Fix committee and indexes
IntersectMBO/cardano-db-sync pull request #1737
Opened 2024-06-17 08:47 UTC by kderme

# Description

Fixes https://github.com/IntersectMBO/cardano-db-sync/issues/1735. Also fixes the indexes

# Checklist

- [ ] Commit sequence broadly makes sense
- [x] Commits have useful messages
- [ ] New tests are added if needed and existing tests are updated
- [ ] Any changes are noted in the [changelog](https://github.com/IntersectMBO/cardano-db-sync/blob/master/cardano-db-sync/CHANGELOG.md)
- [x] Code is formatted with [`fourmolu`](https://github.com/fourmolu/fourmolu) on version 0.10.1.0 (which can be run with `scripts/fourmolize.sh`)
- [ ] Self-reviewed the diff

# Migrations

- [ ] The pr causes a [breaking change](https://github.com/IntersectMBO/cardano-db-sync/blob/master/doc/migrations.md) of type a,b or c
- [ ] If there is a breaking change, the pr includes a database migration and/or a fix process for old values, so that upgrade is possible
- [ ] Resyncing and running the migrations provided will result in the same database semantically

If there is a breaking change, especially a big one, please add a justification here. Please elaborate
more what the migration achieves, what it cannot achieve or why a migration is not possible.

2024-06-17 13:04 UTC, Cmdv requested changes
LGTM just a simple export might need removing

2024-06-17 13:04 UTC, Cmdv commented on cardano-db-sync/src/Cardano/DbSync/Era/Shelley/Query.hs
> -queryPoolUpdateByBlock blkId poolHashId = do
👌 I did find it confusing that we had db queries inside of cardano-db-sync but was too scared to move 😅

2024-06-17 15:58 UTC, sgillespie commented
Looks like you have some tests to update:

```
force-indexes
        check force-index adds indexes:                                          FAIL (51.21s)
          test/Test/Cardano/Db/Mock/Validate.hs:153:
          unexpected number of indexes: got 171 expected 172
          Use -p '/Conway unit tests.Command Line Arguments.force-indexes.check force-index adds indexes/' to rerun this test only.
        check no force-index doesn't add indexes:                                FAIL (51.22s)
          test/Test/Cardano/Db/Mock/Validate.hs:153:
          unexpected number of indexes: got 108 expected 107
          Use -p '/Conway unit tests.Command Line Arguments.force-indexes.check no force-index doesn'\''t add indexes/' to rerun this test only.
```

2024-06-17 18:03 UTC, sgillespie commented on cardano-db-sync/src/Cardano/DbSync/Ledger/Types.hs
> +  , apGovActionState :: !(Maybe (ConwayGovState StandardConway))
:ok_hand: This will come in handy for testing, too

2024-06-27 11:48 UTC, Cmdv reviewed
LGTM just a couple of little things. Also do we need documentation for `EnableFutureGenesis` in the docs?

2024-07-02 17:47 UTC, kderme commented
Done at https://github.com/IntersectMBO/cardano-db-sync/pull/1744

2024-07-02 17:47 UTC, closed without merging